### ISSUE TITLE
Crash by UnicodeDecodeError

### ISSUE THREAD

**Issue by yugecin** [yugecin/pypanel#2]
Same as before, caused by window title
```
/usr/local/bin/pypanel:276: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if task.name != name:
Traceback (most recent call last):
  File "/usr/local/bin/pypanel", line 998, in <module>
    PyPanel(display.Display())
  File "/usr/local/bin/pypanel", line 101, in __init__
    self.loop(self.display, self.root, self.window, self.panel)
  File "/usr/local/bin/pypanel", line 860, in loop
    self.setName(win, tasks.tasks[e.window.id])
  File "/usr/local/bin/pypanel", line 283, in setName
    self.drawText(task, x, task.x2-x-P_SPACER)
  File "/usr/local/bin/pypanel", line 143, in drawText
    title = obj.name.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 39: ordinal not in range(128)
```

**Comment by yugecin** [comment]
Reproduce: goto this page: [installing bugzilla quickstart](https://bugzilla.readthedocs.io/en/latest/installing/quick-start.html)
